### ISSUE TITLE
New Client Library Tracking Issue

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#1447]
## Goals
* Parallelism
* Operation-separation (Tor circuit support)
* Modularity
* Correctness in all cases (crashes, restarts, …)

## Sub-tasks
- [x] Generalized `Decode` trait (#1633)
- [x] Define interfaces and implement state machine executor (#1621)
- [x] Move `ClientModuleGen` to `fedimint-client` #1828 
- [x] Ecash client
- [ ] Wallet client
- [ ] Lightning client
  - [x] Send
  - [x] Receive
  - [ ] Gateway
- [ ] Join federation
- [ ] Check for compatibility with federation via [versions](https://github.com/fedimint/fedimint/pull/2265) RPC 
- [ ] Report if consensus isn't running via https://github.com/fedimint/fedimint/pull/2272
- [ ] `fedimint-cli ng` can display some form of transaction history

**Comment by justinmoon** [comment]
Close in favor of https://github.com/fedimint/fedimint/issues/2514
