### ISSUE TITLE
Tor Support Tracking Issue

### ISSUE THREAD

**Issue by oleonardolima** [fedimint/fedimint#2610]
## Description
In the full-fledged version, fedimint clients should have full Tor support, being able to connect to federation peers through Tor network, either if they are hosted in clearnet (hostnames) or through hidden services (onion addresses).

It should also have `OperationId` stream isolation, to ensure that different `OperationId`'s rely on and have different connections, that said different Tor circuits, it's a great feature to avoid deanonymization due to correlations made by the connections and `OperationId`'s being requested by the client.

It can be split into some steps/milestones:

1. **refactor: jsonrpsee and add support to generic data streams and proxying:**
    - [x] https://github.com/paritytech/jsonrpsee/issues/1162
    - [x] https://github.com/paritytech/jsonrpsee/issues/870
    - [x] https://github.com/paritytech/jsonrpsee/pull/1168
    - [x] https://github.com/paritytech/jsonrpsee/issues/1241
    - [x] https://github.com/fedimint/fedimint/pull/3454
    - [x] https://github.com/fedimint/fedimint/pull/3934
    - [x] https://github.com/fedimint/fedimint/pull/3440

2. **feat: add initial Tor support, without `OperationId` stream isolation:** https://github.com/fedimint/fedimint/issues/4752
    - [x] feat: add initial Tor support, connection to `hostname` + `onion addresses (hidden services)` https://github.com/fedimint/fedimint/pull/5443
    - [ ] feat: add initial Tor support, support for `onion addresses` into `InviteCode`

4. **feat: add full-fledged Tor support, with `OperationId` stream isolation:**
    - [ ] refactor: make `WsFederationApi` based on `OperationId`, becoming`WsOperationIdFederationApi`
    - [ ] refactor: make `WsFederationApi` clients based on `Connector` variant of `WsOperationIdFederationApi`
    - [ ] ~~refactor: add new `Tor` as `Connector` variant, with `WsClient` over arti `DataStream`~~

--

### Chores:
- [x] chore: [`arti-hyper`](https://tpo.pages.torproject.net/core/doc/rust/arti_hyper/index.html) assessment integration and usage to support SOCKS5 proxy with jsonrpsee
- [x] chore: [`arti-client`](https://tpo.pages.torproject.net/core/doc/rust/arti_client/index.html#more-advanced-usage) assessment on json-rpc library support and integration

### References:
- https://github.com/fedimint/fedimint/issues/15
- https://github.com/fedimint/fedimint/issues/391
- jsonrpsee socks support example: https://github.com/elsirion/jsonrpsee/commit/8ec1b4a87de4d9f0b2eebef67f06fb5754c8c414
- call & general notes: https://hackmd.io/@leonardolima/ByyrfsEUh

**Comment by justinmoon** [comment]
Closing https://github.com/fedimint/fedimint/issues/391 in favor of this one

**Comment by elsirion** [comment]
> chore: [arti-hyper](https://tpo.pages.torproject.net/core/doc/rust/arti_hyper/index.html) assessment integration and usage to support SOCKS5 proxy with jsonrpsee

Isn't the whole point of `arti-hyper` that it doesn't use SOCKS5 and instead establishes in-process Tor connections via `arti`?

**Comment by justinmoon** [comment]
In the call yesterday @oleonardolima mentioned he was making some changes to jsonrpsee. Keep us updated here!

**Comment by justinmoon** [comment]
Call: https://github.com/paritytech/jsonrpsee/pull/1168

**Comment by oleonardolima** [comment]
**update:** the [refactor: update and turn WsTransportClientBuilder generic](https://github.com/paritytech/jsonrpsee/pull/1168) on jsonrpsee landed to master and will probably get in the[ v0.21 release](https://github.com/paritytech/jsonrpsee/issues/1241).

I'll be focusing on fedimint side now 🎉
