### ISSUE TITLE
Devimint improvements

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint#2754]
After closing the [initial devimint issue](https://github.com/fedimint/fedimint/issues/2101), let's use this issue to record any ideas to improve devimint:

- [ ] `dev-fed` Flag to not register gateways (useful for testing "join federation" feature in gateway ui)
- [x] Ability to run 2 federations at once. Useful for testing multi-federation feature in gateway. Related to https://github.com/fedimint/fedimint/issues/3161
- [x] Some way to kill devimint and child processes and wait for them all to terminate. Currently `devimint` will terminate before the `fedimintd` process it spawns. [Relevant comment](https://github.com/fedimint/fedimint/pull/2873#issuecomment-1660226736)
- [x] Maintain `FM_PID_FILE` https://github.com/fedimint/fedimint/pull/2732
- [ ] `devimint env` sets aliases (see `scripts/aliases.sh`)
- [x] don't use `fedimint-legacy-client`, use `fedimint-client`
- [ ] ability to restart `fedimintd`. Currently to do this you can replace [these lines](https://github.com/fedimint/fedimint/blob/127ee6aa20760bf87c6aa2cca5974e81cd46ce15/scripts/build.sh#L14-L18) with `FM_TEST_DIR=<some fixed directory`. Then you can stop mprocs and start it again and the same configs will be retained.
- [ ] rename `dev-fed` command to like `with-configs` and `run-ui` to like `without-configs`. Or maybe just have one `federation` command and have a flag for `--skip-dkg`?
- [ ] 3rd lightning node? https://github.com/fedimint/fedimint/issues/2619
- [ ] Ability to kill or restart individual child processes https://github.com/fedimint/fedimint/issues/2274
- [ ] Run multiple `dev-fed` with shared daemons and nodes - https://github.com/fedimint/fedimint/issues/3985

**Comment by justinmoon** [comment]
We currently save `fedimintd` / `gatewayd` configs to a `cfg` directory:

```
$ ls $FM_TEST_DIR
bitcoin/  cfg/  cln/  electrs/  env  esplora/  lnd/  logs/  ready
$ ls $FM_TEST_DIR/cfg
```

I think it would be better to just save them to `FM_TEST_DIR/gatewayd`, `FM_TEST_DIR/fedimintd-0`, `FM_TEST_DIR/fedimintd-`, and so on. No need to nest configs an extra level deeper.

**Comment by elsirion** [comment]
Looks mostly done, all the low-hanging fruits have been picked, the remainder might not be that important.
