### ISSUE TITLE
0.2.0 Release Docs/Docker Update Checklist

### ISSUE THREAD

**Issue by EthnTuttle** [fedimint/fedimint#3737]
- [x] Example Module repo
- [x] Docker folder
- [x] Fedimint UI repo
- [x] Review recovery tool docs

CC: @Kodylow

**Comment by douglaz** [comment]
Basic recovery tool docs review has been done on https://github.com/fedimint/fedimint/pull/3777
