### ISSUE TITLE
v0.3 release planning

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4047]
I think we should target a v0.3 release in Feb 2024, it won't be a big upgrade with many features but rather a first real test for our backwards compatibility strategy.

As such, I see the following must-haves:
* [x] State machine migrations for client upgrades #4282
  * [x] About one example migration to test it (e.g. #3820)
* API version handling in the client
  * [x] Gateway API versioning
  * [x] ~Test Federation API version change with dummy module (we currently don't have anything that would require an actual API change right now)~ We did a few actual API changes now and @dpc fixed some bugs iirc.
* More testing
  * [x] Backwards compatibility tests (#4010)
  * [ ] Module-level tests for non-happy-paths (timeouts, connection issues, …)
* [ ] Formalize our stability guarantees (#3978)
* Smaller, high-impact features
  * [x] Guardian config backup through admin UI, we got some feedback from people that don't fully understand their deployment method and were worried about key backups (#4039)
  * *Open for more as long as they are easy to achieve and solve real problems*

Since there doesn't seem to be anything we need to upgrade on the server side right now I'd say consensus migrations are out-of-scope for now.
