### ISSUE TITLE
Release 0.2.2

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4205]
Issue to track backports and their testing status.

## TODO
* [ ] Manual testing (see below) with fully operational and degraded federations
* [x] Compatibility testing 0.2.1 <> 0.2.2, 0.2.2 <> master

## Changes
* [chore: speed up recovery by batching and streaming](https://github.com/fedimint/fedimint/commit/ee600152adfb55085ab00576675972186d1a53e2)
  * [x] Review
  * [ ] Manual testing
* Bumping deps: `h2`, `ahash`, `shlex` (no testing req)
* Efficient session counting ([5401bce](https://github.com/fedimint/fedimint/pull/4089/commits/5401bce8f3d9c06d0267ea7a1a2e102822c58f0b), [be8ef77](https://github.com/fedimint/fedimint/pull/4089/commits/be8ef77aec7c6daf7fa909bd58670f60d6f3fcbd), #4203)
  * [x] Review
  * [ ] Manual testing
* [mark JsonRpcClientError:Call as retryable regardless of code](https://github.com/fedimint/fedimint/commit/8b57b8a1502d95ad931048d16f9ceeb32a4398f7) + #4112
  * [x] Review
  * [ ] Manual testing
* [chore: expose fedimint-dbtool](https://github.com/fedimint/fedimint/commit/1a441e11b757f8bdf186cd40224eb6c93cdaabda) (build system, no testing required)
* [fix: use fedimint-aleph-bft](https://github.com/fedimint/fedimint/commit/90b7d6c574052f09f97f4abe2d8fb9e9b5b899aa) + [fix: downgrade alephbft](https://github.com/fedimint/fedimint/commit/4b0f47c514083096778c188f19aeb01adb7e109e)
  * [x] Review (we messed up the first time around, but now it's quite solid imo)
  * [ ] Manual testing
* [feat(ln-client): make LN gateway known upfront](https://github.com/fedimint/fedimint/commit/93df3a00c17cd76169ce33f96db0d196fc3cd05e)
  * [x] Review
  * [ ] Manual testing
* [chore: upgrade tonic_lnd to 0.2.0](https://github.com/fedimint/fedimint/commit/01c7ee6daa8213d0a0429e8436516e897fd67822)
  * [x] Review (included @justinmoon's fix for multiple certificate ordering)
  * [ ] Manual testing
* [fix: log warning on invalid header signature from peer](https://github.com/fedimint/fedimint/commit/85637e84bb9a2ad119c0a91e6280f74225e3b97c)
  * [x] Review
* [feat: expose pending accepted consensus items in endpoint](https://github.com/fedimint/fedimint/commit/6a81b5f174e716af57c78fca28e4ab093ce498d1) + #4180 
  * [x] Review
  * [ ] ~Manual testing~ (not needed since funcitonality is no used yet except for debugging)
* TODO: backport exponential slowdown fix

## Process Learnings
* We need to be more conservative with what we a) merge to master and b) backport, lot's of fixups in here that make it hard to track what actually happened

**Comment by justinmoon** [comment]
Deep dive: https://github.com/fedimint/fedimint/pull/4064 also needs testing on client and gateway

**Comment by justinmoon** [comment]
Brad and DPC have successfully run the backwards compatibility tests against `releases/v0.2` https://github.com/fedimint/fedimint/pull/4215

**Comment by elsirion** [comment]
We've run a rc8 federation for a it now, tested the upgrade process and I did some manual testing with a the rc8 client. I didn't find any issues, so let's cut the release.
