### ISSUE TITLE
Anto DoS roadmap

### ISSUE THREAD

**Issue by elsirion** [fedimint/fedimint#4385]
* [ ] 0.3: Enable fee charging by the federation
  * [ ] Requires client improvement to coin selection
* [ ] 0.4: [Anonymous, single-sig API usage tokens](https://github.com/fedimint/fedimint/discussions/1440#discussioncomment-8521158)
  * [ ] Spec out architecture
