### ISSUE TITLE
Deterministic client nonce generation and restore

### ISSUE THREAD

**Issue by dpc** [fedimint/fedimint#502]
Some notes:

* [x] Client should generate nonces & blindnonces deterministically, by keeping track of some sequence counter and using a secret root seed.
* [x] https://github.com/fedimint/fedimint/pull/928#discussion_r1043369157 fix #1121
* [x] Mark invalid transactions in consensus history, and then use it to skip over them in restore. #1117
* [ ] print some stats about backup/restored data in the output of `fedimint-cli` (possibly just the same thing that `info` prints)
* [x] add integration/e2e tests of some kind to always sanity check that backup&recovery are working OK. #1124
* [x] high level docs #1108
* [ ]   ~~Lock the client during recovery process (Moved to #1120)~~

**Comment by dpc** [comment]
@elsirion Is there any downside from using public-key derivation-supporting scheme here? Is it doably? My crypto-fu is not strong enough to tell.

**Comment by elsirion** [comment]
> Is there any downside from using public-key derivation-supporting scheme here? Is it doably?

There are two keys per e-cash token:

* **Spend key**: secret key needed to spend the token, the associated pub key is the nonce. You could do some bip32-like derivation, but all it gets you is deanonymizing yourself if you ever leak your xpub. Not very appealing imo.
* **Blinding key**: this isn't really an asymmetric key, so there's no way to have a derivable pub key.

So in short I think the answer is no.

> On restore from seed, the client needs to scan linearly blinded nonces and check with the federation which ones were were already issued; then it can check which ones were already spent as well.

Ideally we'd use some privacy-preserving way of scanning only for our blind nonce, something like client side block filters maybe where we combine a bunch of epochs into one "block" and clients can check which ones they need to download? Alternatively if we can do daily full backups we might just download everything since the last snapshot till the date the user said they lost access.

> Storing blindednonce by federation and clients being able to query them could be used for multi-device setups and watch-only wallets in some future.

Querying the federation is a major privacy concern. We'll need to find a trade-off between downloading the entire history and only querying our blind nonces which links all past payments. So I don't think we should rely on this for anything but emergencies like having lost your phone. I think if someone wants multi-device support they should run clientd on a server and have some client phone app, just like with LN today which has the same problem of a lot of state.

**Comment by dpc** [comment]
Oh well, multi-device support is out then.

**Comment by justinmoon** [comment]
DPC mentioned this will be easier once modularization effort is complete.

**Comment by dpc** [comment]
OK, closing it. Delegated one, the other one seems rather cosmetic.
