### ISSUE TITLE
Bolt 12 Tracking Issue

### ISSUE THREAD

**Issue by m1sterc001guy** [fedimint/fedimint#6223]
This issue is intended to outline the tasks necessary for "integrating" Bolt 12 into Fedimint. The process of integrating has different steps and this issue outlines those steps. Note that this issue just outlines potential tasks, it does not assign a priority.

For further discussion on Bolt 12 see [this issue](https://github.com/fedimint/fedimint/issues/559) and [discussion](https://github.com/fedimint/fedimint/discussions/1507).

- [ ] Support LDK Gateway creating amount and amount-less offers that are payable to the Lightning operator (not fedimint clients).
- [ ] Support LDK Gateway paying BOLT12 offers, directly from the Lightning operator (not on behalf of a fedimint client)
- [ ] Support fedimint clients paying BOLT12 offers via LDK Gateway
- [ ] Support fedimint clients paying BOLT12 offers via LND/LNDK
- [ ] Support fedimint clients receiving ecash via BOLT12 via LDK
